### ISSUE TITLE
Cannot decrypt

### ISSUE THREAD

**Issue by ALMLAMBO** [GoogleCloudPlatform/dotnet-docs-samples#1122]
Hi,

I am doing this tutorial from google cloud docs: [https://cloud.google.com/kms/docs/encrypt-decrypt](https://cloud.google.com/kms/docs/encrypt-decrypt) and encryption is ok but when I start decrypting, it throws this exception: 
```
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode=InvalidArgument, Detail="Decryption failed: verify that 'name' refers to the correct CryptoKey.")
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Kms.V1.KeyManagementService.KeyManagementServiceClient.Decrypt(DecryptRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass10_0.<WithCallSettingsOverlay>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
```
This is my code for decryption:

```
KeyManagementServiceClient client =
				KeyManagementServiceClient.Create();

			CryptoKeyName name = new CryptoKeyName(
				projectId, locationId, keyRingId, keyId);

			DecryptRequest request = new DecryptRequest {
				CryptoKeyName = name,
				Ciphertext = ByteString.FromBase64(new string(""))
			};

			DecryptResponse decryptResponse = client
				.Decrypt(request);
```
This is done on C#. How can I decrypt successfully?

**Comment by amanda-tarafa** [comment]
@sethvargo I've assigned to you since you'll probably have a better context than I for this one.

**Comment by sethvargo** [comment]
From the same, it looks like you're decrypting the empty string? Can you share more about how you generated your ciphertext?

**Comment by ALMLAMBO** [comment]
string message = "This is a message";

**Comment by jskeet** [comment]
But are you definitely decrypting the right value? This code looks odd:

```csharp
DecryptRequest request = new DecryptRequest {
    CryptoKeyName = name,
    Ciphertext = ByteString.FromBase64(new string(""))
};
```

Can you show us a short but *complete* example?

**Comment by ALMLAMBO** [comment]
```
DecryptRequest request = new DecryptRequest {
				CryptoKeyName = name,
				Ciphertext = ByteString.CopyFrom(
					Encoding.UTF8.GetBytes("This is a message"))
			};
```

**Comment by jskeet** [comment]
That's not going to work, because "This is a message" isn't encrypted data.

The `ByteString` you put into `Ciphertext` needs to be the result from a previous `Encrypt` operation.

**Comment by ALMLAMBO** [comment]
Now it throws this exception:
```
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode=InvalidArgument, Detail="Decryption failed: the ciphertext is invalid.")
```

**Comment by ALMLAMBO** [comment]
Thanks a lot!

**Comment by jskeet** [comment]
Closing as I assume from the last comment that this is now working.
