### ISSUE TITLE
[Pub/Sub]: Error - Wildcard resource ids must not contain / (Parameter 'value') using PullMessagesAsync

### ISSUE THREAD

**Issue by bfrey1** [GoogleCloudPlatform/dotnet-docs-samples#1267]
Hi!

The following innocent code snippet keeps breaking when trying to pull the published messages:
```         
	PublishMessagesAsyncSample _publishMessagesAsyncSample = new PublishMessagesAsyncSample();
	PullMessagesAsyncSample _pullMessagesAsyncSample = new PullMessagesAsyncSample();

	List<string> messageTexts = new List<string> { "Hello World!", "Good day.", "Bye bye." };

	var output = await _publishMessagesAsyncSample.PublishMessagesAsync(projectId, topicId, messageTexts);
	Console.WriteLine("output=" + output);

	// Pull the Message to confirm it is valid
	try
	{
		// --> this part will break
		var result = await _pullMessagesAsyncSample.PullMessagesAsync(projectId, subscriptionId, false);
		Console.WriteLine("result=" + result);
	}
	catch (Exception exception)
	{
		Console.WriteLine($"An error ocurred: {exception.Message}");
	}
```

Throws the following error:
```
Published message 2033655843200036
Published message 2033655843200034
Published message 2033655843200035
output=3
Unhandled exception. System.ArgumentException: Wildcard resource ids must not contain / (Parameter 'value')
   at Google.Api.Gax.PathTemplate.Segment.ValidateWildcardValue(String value)
   at Google.Api.Gax.PathTemplate.ValidateResourceIds(String[] resourceIds)
   at Google.Api.Gax.PathTemplate.ExpandWithService(String serviceName, String[] resourceIds)
   at Google.Api.Gax.PathTemplate.Expand(String[] resourceIds)
   at Google.Cloud.PubSub.V1.SubscriptionName.ToString()
   at Google.Cloud.PubSub.V1.StreamingPullRequest.set_SubscriptionAsSubscriptionName(SubscriptionName value)
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.SingleChannel.HandleStartStreamingPullWithoutBackoff()
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.SingleChannel.StartStreamingPull()
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.SingleChannel.StartAsync()
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter.GetResult()
   at Google.Cloud.PubSub.V1.Tasks.Extensions.<>c__DisplayClass4_0.<<ConfigureAwaitHideErrors>g__Inner|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult()
   at Google.Cloud.PubSub.V1.Tasks.Extensions.<>c__DisplayClass1_0`1.<<ConfigureAwaitWithFinally>g__Inner|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult()
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.<>c__DisplayClass24_0.<<StopAsync>b__1>d.MoveNext()

```

Perhaps the issue lies in me using .net 5?
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>my_namespace</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="2.4.0" />
    <PackageReference Include="Xunit" Version="2.4.1" />
  </ItemGroup>

</Project>
```

Any help is much appreciated! :)

**Comment by jskeet** [comment]
What is the value of `subscriptionId`? I strongly suspect that's the problem - I suspect you're passing in a full resource name there, instead of just the subscription ID.

**Comment by bfrey1** [comment]
@jskeet : Thanks, you're right... such an easy fix. Did not put that together with error message, though in hindsight seems plausible.
