### ISSUE TITLE
[PubSub]: Avro schema test are flaky

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1588]
Examples of failures [here](https://fusion2.corp.google.com/invocations/8570fa78-0d27-499b-a907-f5911be55094/targets/github%2Fdotnet-docs-samples%2Fappengine%2Fflexible%2FPubsub;config=default/tests) and [here](https://fusion2.corp.google.com/invocations/c90c5aeb-0499-4bf1-baf1-b0dc73927f7b/targets/github%2Fdotnet-docs-samples%2Fappengine%2Fflexible%2FPubsub;config=default/tests)

**Comment by amanda-tarafa** [comment]
More info [here](https://source.cloud.google.com/results/invocations/453fb8ab-4146-4d73-bbc8-909807744bf6/log) but copying details as retention on those logs may expire:

```
Failed CreateAvroSchemaTest.CreateAvroSchema [292 ms]
  Error Message:
   Assert.Equal() Failure
Expected: { "name": "projects/dotnet-docs-samples-tests/schemas/testAvroSchemaForSchemaCreation67371676-2904-47a2", "type": "AVRO", "definition": "{\r\n  \"type\":\"record\",\r\n  \"name\":\"State\",\r\n  \"namespace\":\"utilities\",\r\n  \"doc\":\"A list of states in the United States of America.\",\r\n  \"fields\":[\r\n    {\r\n      \"name\":\"name\",\r\n      \"type\":\"string\",\r\n      \"doc\":\"The common name of the state.\"\r\n    },\r\n    {\r\n      \"name\":\"post_abbr\",\r\n      \"type\":\"string\",\r\n      \"doc\":\"The postal code abbreviation of the state.\"\r\n    }\r\n  ]\r\n}\r\n" }
Actual:   { "name": "projects/dotnet-docs-samples-tests/schemas/testAvroSchemaForSchemaCreation67371676-2904-47a2", "type": "AVRO", "definition": "{\r\n  \"type\":\"record\",\r\n  \"name\":\"State\",\r\n  \"namespace\":\"utilities\",\r\n  \"doc\":\"A list of states in the United States of America.\",\r\n  \"fields\":[\r\n    {\r\n      \"name\":\"name\",\r\n      \"type\":\"string\",\r\n      \"doc\":\"The common name of the state.\"\r\n    },\r\n    {\r\n      \"name\":\"post_abbr\",\r\n      \"type\":\"string\",\r\n      \"doc\":\"The postal code abbreviation of the state.\"\r\n    }\r\n  ]\r\n}\r\n", "revisionId": "9deb0199", "revisionCreateTime": "2023-01-28T04:12:52.182Z" }
  Stack Trace:
     at CreateAvroSchemaTest.CreateAvroSchema() in T:\src\github\dotnet-docs-samples\pubsub\api\Pubsub.Samples.Tests\CreateAvroSchemaTest.cs:line 36
```

```
Failed CreateProtoSchemaTest.CreateProtoSchema [160 ms]
  Error Message:
   Assert.Equal() Failure
Expected: { "name": "projects/dotnet-docs-samples-tests/schemas/testProtoSchemaForSchemaCreation5e0ac587-bd93-4fd0", "type": "PROTOCOL_BUFFER", "definition": "syntax = \"proto3\";\r\n\r\npackage utilities;\r\noption java_outer_classname = \"StateProto\";\r\n\r\nmessage State {\r\n  string name = 1;\r\n  string post_abbr = 2;\r\n}\r\n" }
Actual:   { "name": "projects/dotnet-docs-samples-tests/schemas/testProtoSchemaForSchemaCreation5e0ac587-bd93-4fd0", "type": "PROTOCOL_BUFFER", "definition": "syntax = \"proto3\";\r\n\r\npackage utilities;\r\noption java_outer_classname = \"StateProto\";\r\n\r\nmessage State {\r\n  string name = 1;\r\n  string post_abbr = 2;\r\n}\r\n", "revisionId": "0a8a452d", "revisionCreateTime": "2023-01-28T04:12:55.870Z" }
  Stack Trace:
     at CreateProtoSchemaTest.CreateProtoSchema() in T:\src\github\dotnet-docs-samples\pubsub\api\Pubsub.Samples.Tests\CreateProtoSchemaTest.cs:line 36
```

**Comment by Rishabh-V** [comment]
Assigning to @hemanshv as he has worked on AppEngine/PubSub samples in the past. I will work with him as needed.

**Comment by amanda-tarafa** [comment]
Downgrading to P3, we have explored options internally and still we don't have much to go on. We'll keep the issue open for 6 more months to see if this happens again, else we'll close it as transient.

**Comment by amanda-tarafa** [comment]
Thanks @cy-yun ! Closed by #3100
