### ISSUE TITLE
[Storage]: Compose object test is flaky

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#2038]
Log [here](https://source.cloud.google.com/results/invocations/778557d3-7adf-4b9c-8bff-fd3227a719c5/log)

```
Failed ComposeObjectTest.ComposeObject [611 ms]
  Error Message:
   Google.GoogleApiException : The service storage has thrown an exception. HttpStatusCode is BadRequest. Cannot compose object with destination storage class COLDLINE from source components that have different storage classes (STANDARD)
  Stack Trace:
     at Google.Apis.Requests.ClientServiceRequest`1.ParseResponse(HttpResponseMessage response)
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at ComposeObjectSample.ComposeObject(String bucketName, String firstObjectName, String secondObjectName, String targetObjectName) in /tmpfs/src/github/dotnet-docs-samples/storage/api/Storage.Samples/ComposeObject.cs:line 39
```

**Comment by mahendra-google** [comment]
The compose object flaky test issue is fixed by PR #3344 .
