### ISSUE TITLE
Spanner's TestDml() fails.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/dotnet-docs-samples#713]
```
[xUnit.net 00:00:01.57]   Starting:    SpannerTest
[xUnit.net 00:01:55.83]     GoogleCloudSamples.Spanner.SpannerTests.TestDml [FAIL]
[xUnit.net 00:01:55.83]       System.AggregateException : One or more errors occurred. (An invalid argument was sent to Spanner.)
[xUnit.net 00:01:55.83]       ---- Google.Cloud.Spanner.Data.SpannerException : An invalid argument was sent to Spanner.
[xUnit.net 00:01:55.83]       -------- Grpc.Core.RpcException : Status(StatusCode=InvalidArgument, Detail="Unrecognized name: LastUpdateTime [at 1:19]\nUPDATE Albums SET LastUpdateTime = PENDING_COMMIT_TIMESTAMP() WHERE SingerId = 1\n                  ^")
[xUnit.net 00:01:55.83]       Stack Trace:
[xUnit.net 00:01:55.83]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[xUnit.net 00:01:55.83]            at System.Threading.Tasks.Task.Wait()
[xUnit.net 00:01:55.83]         c:\Users\rennie\gitrepos\dotnet-docs-samples\spanner\api\Spanner\Program.cs(2790,0): at GoogleCloudSamples.Spanner.Program.UpdateUsingDmlWithTimestamp(String projectId, String instanceId, String databaseId)
[xUnit.net 00:01:55.83]         c:\Users\rennie\gitrepos\dotnet-docs-samples\spanner\api\Spanner\Program.cs(2959,0): at GoogleCloudSamples.Spanner.Program.<>c.<Main>b__95_33(UpdateUsingDmlWithTimestampOptions opts)
[xUnit.net 00:01:55.83]         C:\Users\rennie\gitrepos\dotnet-docs-samples\commandlineutil\Lib\VerbMap.cs(53,0): at GoogleCloudSamples.VerbMap`1.<>c__DisplayClass9_0`1.<Add>b__0(Object a)
[xUnit.net 00:01:55.83]         C:\Users\rennie\gitrepos\dotnet-docs-samples\commandlineutil\Lib\VerbMap.cs(90,0): at GoogleCloudSamples.VerbMap`1.Run(String[] args, Parser parser)
[xUnit.net 00:01:55.83]         c:\Users\rennie\gitrepos\dotnet-docs-samples\spanner\api\Spanner\Program.cs(2989,0): at GoogleCloudSamples.Spanner.Program.Main(String[] args)
[xUnit.net 00:01:55.83]         C:\Users\rennie\gitrepos\dotnet-docs-samples\testutil\TestUtil.cs(135,0): at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments)
[xUnit.net 00:01:55.83]         c:\Users\rennie\gitrepos\dotnet-docs-samples\spanner\api\SpannerTest\Tests.cs(333,0): at GoogleCloudSamples.Spanner.SpannerTests.TestDml()
[xUnit.net 00:01:55.83]         ----- Inner Stack Trace -----
[xUnit.net 00:01:55.83]         
```

**Comment by jsimonweb** [comment]
This test is now passing.

From System test on Mar 27 2019, 6:42:05
"Passed   GoogleCloudSamples.Spanner.SpannerTests.TestDml"
